name: Android CI

on:
  push:
    branches:
      - '**'  # This matches all branches
  pull_request:
    branches: [ "master" ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Update Gradle Properties
        run: |
          echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=2g" >> gradle.properties
          echo "android.defaults.buildfeatures.buildconfig=true" >> gradle.properties

      - name: Decode Keystore
        if: github.event_name == 'release' || github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.KEYSTORE }}" > keystore.b64
          base64 -d keystore.b64 > app/release-key.jks
          rm keystore.b64

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --info

      - name: Build Release APK
        if: github.event_name == 'release' || github.ref == 'refs/heads/master'
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew assembleRelease --stacktrace --info

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload Release APK
        if: github.event_name == 'release' || github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk

      - name: Upload Release to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

